version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: php_server
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - clientes-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: apptarefas_av1
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - clientes-network

volumes:
  db_data:

networks:
  clientes-network:
    driver: bridge
